### ISSUE TITLE
Proof runs open, but are they used?

### ISSUE THREAD

**Issue by rbraid** [rbraid/HistoMaker#2]
Commit a7ed06170ae9e18c958b0e66ad0e4bbd4fc63729 added the ROOT parallelization library, PROOF, in a attempt to speed up code execution.  When running the program we see the output 

```
 +++ Starting PROOF-Lite with 4 workers +++
Opening connections to workers: OK (4 workers)                 
Setting up worker servers: OK (4 workers)                 
PROOF set to parallel mode (4 workers)
```

However, comparing the parallelized code with the previous version, the average run times are 19.14 and 19.25 respectively.  At best, we would expect ~4x speed increase on a 4 cored machine but .1 seconds difference seems way too small.

@cspitz can you verify that the code is running in PROOF mode, and not just opening PROOF and running single threaded otherwise?

**Comment by cspitz** [comment]
I'm working on fixing this. I have an issue with rootcint right now that I can't resolve, so I am trying to get on the Linux machine. However, I can't ssh into it at the moment. I believe that problem is not on my end, so hopefully it will be resolved soon.
